name: web-platform
on: [push]
jobs:
  collect-frontmatter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: git config user.name "GitHub Actions"
      - run: git config user.email "actions@github.com"
      - run: npm ci
      - run: node .github/scripts/collect-and-commit-frontmatter.js
