name: web-platform-workflow
on: [push]
jobs:
  collect-frontmatter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: node .github/scripts/collect-and-commit-frontmatter.js
